import uuid
import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.database import SessionLocal
from app.models.campaign import Campaign
from app.models.lead import Lead
from app.models.lead_score import LeadScore
from app.models.outreach import OutreachRecord
from app.models.lead_note import LeadNote, LeadTag
from app.models.lead_contact import LeadContact
from app.models.campaign_recipient import CampaignRecipient
from app.models.email_message import EmailMessage
from app.models.search import SearchHistory
from app.models.google_connection import SheetDestination

client = TestClient(app)

def test_delete_campaign_purges_all_database_data():
    db = SessionLocal()
    uid = uuid.uuid4().hex[:8]
    try:
        # Create an unrelated campaign and lead to ensure they are untouched
        safe_camp = Campaign(
            name=f"Untouched Campaign {uid}",
            business_type="Dentists",
            location="Mumbai",
            status="Active"
        )
        db.add(safe_camp)
        db.flush()

        safe_lead = Lead(
            place_id=f"ChIJ_safe_dental_{uid}",
            business_name="Safe Dental Clinic",
            campaign_id=safe_camp.id,
            email=f"safe_{uid}@dentist.com"
        )
        db.add(safe_lead)
        db.flush()

        # Create target campaign to delete
        camp = Campaign(
            name=f"Campaign To Be Purged {uid}",
            business_type="Solar Installers",
            location="Bangalore",
            status="Active"
        )
        db.add(camp)
        db.flush()
        camp_id = camp.id

        # 1. Search history linked to campaign
        search = SearchHistory(
            campaign_id=camp_id,
            business_type="Solar Installers",
            location="Bangalore",
            query=f"Solar Installers in Bangalore {uid}",
            raw_result_count=10,
            unique_count=5,
            duplicate_count=1,
            status="Completed"
        )
        db.add(search)
        db.flush()
        search_id = search.id

        # 2. Lead directly linked to campaign
        lead1 = Lead(
            place_id=f"ChIJ_sunpower_{uid}",
            business_name="SunPower Direct",
            campaign_id=camp_id,
            email=f"info_{uid}@sunpower.com"
        )
        db.add(lead1)
        db.flush()

        # 3. Lead generated by search
        lead2 = Lead(
            place_id=f"ChIJ_greenvolt_{uid}",
            business_name="GreenVolt Systems",
            search_id=search_id,
            email=f"contact_{uid}@greenvolt.in"
        )
        db.add(lead2)
        db.flush()

        # 4. Lead linked via recipient
        lead3 = Lead(
            place_id=f"ChIJ_ecoenergy_{uid}",
            business_name="EcoEnergy Hub",
            email=f"hello_{uid}@ecoenergy.com"
        )
        db.add(lead3)
        db.flush()

        # 5. Child records for lead1
        db.add(LeadScore(lead_id=lead1.id, total_score=85, priority="HIGH", reasons="Has verified email"))
        db.add(OutreachRecord(lead_id=lead1.id, status="NEW", priority="HIGH"))
        db.add(LeadNote(lead_id=lead1.id, content="Initial lead note"))
        db.add(LeadTag(lead_id=lead1.id, tag="High Priority"))
        db.add(LeadContact(lead_id=lead1.id, name="Rahul Sharma", email="rahul@sunpower.com"))

        # 6. Campaign recipient
        recipient1 = CampaignRecipient(
            campaign_id=camp_id,
            lead_id=lead1.id,
            email="info@sunpower.com",
            status="PENDING"
        )
        recipient2 = CampaignRecipient(
            campaign_id=camp_id,
            lead_id=lead3.id,
            email="hello@ecoenergy.com",
            status="PENDING"
        )
        db.add(recipient1)
        db.add(recipient2)
        db.flush()

        # 7. Email message
        db.add(EmailMessage(
            campaign_id=camp_id,
            recipient_id=recipient1.id,
            lead_id=lead1.id,
            recipient_email="info@sunpower.com",
            subject="Solar Inquiry",
            rendered_body="Hello from Duo Systems",
            status="SENT"
        ))

        # 8. Sheet destination
        db.add(SheetDestination(
            campaign_id=camp_id,
            spreadsheet_id="test_sheet_123",
            spreadsheet_title="Solar Leads Export",
            worksheet_title="Bangalore Solar"
        ))

        db.commit()

        safe_camp_id = safe_camp.id
        safe_lead_id = safe_lead.id
        lead1_id = lead1.id
        lead2_id = lead2.id
        lead3_id = lead3.id
        rec1_id = recipient1.id
        rec2_id = recipient2.id

    finally:
        db.close()

    # Now call the DELETE API endpoint
    del_res = client.delete(f"/api/campaigns/{camp_id}")
    assert del_res.status_code == 204

    # Verify everything has been completely deleted from the database
    verify_db = SessionLocal()
    try:
        # Campaign is gone
        assert verify_db.query(Campaign).filter(Campaign.id == camp_id).first() is None

        # Search is gone
        assert verify_db.query(SearchHistory).filter(SearchHistory.id == search_id).first() is None
        assert verify_db.query(SearchHistory).filter(SearchHistory.campaign_id == camp_id).first() is None

        # Associated leads are gone
        assert verify_db.query(Lead).filter(Lead.id == lead1_id).first() is None
        assert verify_db.query(Lead).filter(Lead.id == lead2_id).first() is None
        assert verify_db.query(Lead).filter(Lead.id == lead3_id).first() is None

        # Associated child records are gone
        assert verify_db.query(LeadScore).filter(LeadScore.lead_id == lead1_id).first() is None
        assert verify_db.query(OutreachRecord).filter(OutreachRecord.lead_id == lead1_id).first() is None
        assert verify_db.query(LeadNote).filter(LeadNote.lead_id == lead1_id).first() is None
        assert verify_db.query(LeadTag).filter(LeadTag.lead_id == lead1_id).first() is None
        assert verify_db.query(LeadContact).filter(LeadContact.lead_id == lead1_id).first() is None

        # Recipients & email messages are gone
        assert verify_db.query(CampaignRecipient).filter(CampaignRecipient.campaign_id == camp_id).first() is None
        assert verify_db.query(CampaignRecipient).filter(CampaignRecipient.id.in_([rec1_id, rec2_id])).first() is None
        assert verify_db.query(EmailMessage).filter(EmailMessage.campaign_id == camp_id).first() is None

        # Sheet destinations are gone
        assert verify_db.query(SheetDestination).filter(SheetDestination.campaign_id == camp_id).first() is None

        # Untouched campaign and lead STILL exist
        assert verify_db.query(Campaign).filter(Campaign.id == safe_camp_id).first() is not None
        assert verify_db.query(Lead).filter(Lead.id == safe_lead_id).first() is not None

        # Clean up the safe campaign
        client.delete(f"/api/campaigns/{safe_camp_id}")

    finally:
        verify_db.close()
